# Generated by Django 5.0.6 on 2026-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='RepairoX', max_length=120)),
                ('announcement', models.CharField(blank=True, help_text='Top promo bar text. Leave empty to hide the bar.', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('hours', models.CharField(blank=True, help_text='e.g. Sat–Thu: 9AM–8PM', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('hero_title', models.CharField(blank=True, max_length=150)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300)),
                ('about_text', models.TextField(blank=True, help_text='Shown in the footer. Leave empty to hide.')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
