# Generated by Django 5.2.15 on 2026-06-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='notify_email',
            field=models.EmailField(blank=True, help_text='Order notifications are sent to this address. If empty, the contact email above is used.', max_length=254),
        ),
    ]
